-- Listening-stats scrobble log.
-- One row per playback; drives Listening Stats aggregations across devices.
-- Matches PlayEventEntity (Room) and SbPlayEvent (SupabaseSyncRepository.kt).

create table if not exists public.play_events (
    id             bigint generated by default as identity primary key,
    user_id        uuid not null references auth.users(id) on delete cascade,
    track_id       bigint not null,
    title          text not null default '',
    duration       int  not null default 0,
    artist_id      bigint,
    artist_name    text not null default '',
    album_id       bigint,
    album_title    text,
    album_cover    text,
    audio_quality  text,
    source         text,
    played_at_ms   bigint not null default 0,
    inserted_at    timestamptz not null default now()
);

create index if not exists play_events_user_played_at
    on public.play_events (user_id, played_at_ms desc);

create index if not exists play_events_user_track
    on public.play_events (user_id, track_id);

-- RLS: users can only see/insert their own rows.
alter table public.play_events enable row level security;

create policy "play_events_select_own" on public.play_events
    for select using (auth.uid() = user_id);

create policy "play_events_insert_own" on public.play_events
    for insert with check (auth.uid() = user_id);

create policy "play_events_delete_own" on public.play_events
    for delete using (auth.uid() = user_id);
